param(
  [string]$ToolRoot = (Split-Path -Parent (Split-Path -Parent $PSCommandPath)),
  [string]$StateRoot = (Join-Path $HOME ".dev-triangle"),
  [int]$TimeoutSec = 240
)

$ErrorActionPreference = "Stop"

function Invoke-Mcp {
  param(
    [string]$ServerPath,
    [array]$Messages,
    [int]$TimeoutSec = 60
  )
  $inputText = ($Messages | ForEach-Object { $_ | ConvertTo-Json -Depth 20 -Compress }) -join "`n"
  $inputText += "`n"
  $proc = Start-Process -FilePath $script:Python -ArgumentList @("`"$ServerPath`"") -WorkingDirectory $script:ToolRoot -NoNewWindow -Wait -PassThru -RedirectStandardInput "$env:TEMP\dev-triangle-mcp-in.jsonl" -RedirectStandardOutput "$env:TEMP\dev-triangle-mcp-out.jsonl" -RedirectStandardError "$env:TEMP\dev-triangle-mcp-err.txt"
}

function Invoke-McpServer {
  param(
    [string]$ServerPath,
    [array]$Messages,
    [int]$TimeoutSec = 60
  )
  $inputPath = Join-Path $env:TEMP ("dev-triangle-mcp-in-" + [guid]::NewGuid().ToString("N") + ".jsonl")
  $outputPath = Join-Path $env:TEMP ("dev-triangle-mcp-out-" + [guid]::NewGuid().ToString("N") + ".jsonl")
  $errorPath = Join-Path $env:TEMP ("dev-triangle-mcp-err-" + [guid]::NewGuid().ToString("N") + ".txt")
  ($Messages | ForEach-Object { $_ | ConvertTo-Json -Depth 20 -Compress }) | Set-Content -LiteralPath $inputPath -Encoding UTF8
  $proc = Start-Process -FilePath $script:Python -ArgumentList @("`"$ServerPath`"") -WorkingDirectory $script:ToolRoot -NoNewWindow -Wait -PassThru -RedirectStandardInput $inputPath -RedirectStandardOutput $outputPath -RedirectStandardError $errorPath
  $stdout = Get-Content -Raw -LiteralPath $outputPath
  $stderr = Get-Content -Raw -LiteralPath $errorPath
  if ($proc.ExitCode -ne 0) {
    throw "MCP server exited with $($proc.ExitCode): $stderr"
  }
  return @($stdout -split "`r?`n" | Where-Object { $_.Trim() } | ForEach-Object { $_ | ConvertFrom-Json })
}

$ToolRoot = [System.IO.Path]::GetFullPath($ToolRoot)
$StateRoot = [System.IO.Path]::GetFullPath($StateRoot)
$script:ToolRoot = $ToolRoot
$script:Python = if ($env:DEV_TRIANGLE_PYTHON -and (Test-Path -LiteralPath $env:DEV_TRIANGLE_PYTHON)) {
  $env:DEV_TRIANGLE_PYTHON
} else {
  $codexPython = Join-Path $HOME ".cache\codex-runtimes\codex-primary-runtime\dependencies\python\python.exe"
  if (Test-Path -LiteralPath $codexPython) { $codexPython } else { "python" }
}

$env:DEV_TRIANGLE_HOME = $StateRoot
$env:ANTIGRAVITY_HANDOFF_DIR = Join-Path $StateRoot "antigravity-handoffs"
$env:ANTIGRAVITY_AGY_PRINT_TIMEOUT = "$($TimeoutSec)s"

$DemoRoot = Join-Path $ToolRoot "demo-output\user-demo-project"
$ReportDir = Join-Path $ToolRoot "demo-output"
New-Item -ItemType Directory -Force -Path $DemoRoot, $ReportDir | Out-Null

Set-Content -LiteralPath (Join-Path $DemoRoot "app.py") -Encoding UTF8 -Value @'
def add(a: int, b: int) -> int:
    return a + b


if __name__ == "__main__":
    print(add(2, 3))
'@

Set-Content -LiteralPath (Join-Path $DemoRoot "smoke_test.py") -Encoding UTF8 -Value @'
from app import add


assert add(2, 3) == 5
print("demo smoke passed")
'@

Set-Content -LiteralPath (Join-Path $DemoRoot "README.md") -Encoding UTF8 -Value @'
# User Demo Project

This small project is generated by Dev Triangle MCP's local productization demo.
'@

$server = Join-Path $ToolRoot "server.py"
$init = @{ jsonrpc = "2.0"; id = 1; method = "initialize"; params = @{} }

$handoffMessages = @(
  $init,
  @{
    jsonrpc = "2.0"
    id = 2
    method = "tools/call"
    params = @{
      name = "create_antigravity_handoff"
      arguments = @{
        title = "Productized user-flow demo"
        objective = "Act like the user's local validation agent for this new project. Read the demo project, run the suggested smoke checks, and submit the result through complete_dev_triangle_handoff."
        repoPath = $DemoRoot
        context = "This is the first productized user-facing demo for Dev Triangle MCP. No source changes are required unless a smoke check fails."
        files = @("app.py", "smoke_test.py", "README.md")
        suggestedCommands = @("python -m py_compile app.py smoke_test.py", "python smoke_test.py")
        acceptanceCriteria = "The handoff is complete only when the smoke test passes and a result is submitted through dev-triangle-report MCP."
      }
    }
  }
)

$handoffResponse = Invoke-McpServer -ServerPath $server -Messages $handoffMessages
$handoff = $handoffResponse[-1].result.structuredContent.handoff

$runMessages = @(
  $init,
  @{
    jsonrpc = "2.0"
    id = 2
    method = "tools/call"
    params = @{
      name = "run_antigravity_handoff"
      arguments = @{
        handoff = $handoff.id
        repoPath = $DemoRoot
        executionStyle = "agy_print"
        timeoutSec = $TimeoutSec
        waitForResult = $true
        resultTimeoutSec = 60
        pollIntervalSec = 3
      }
    }
  }
)

$runResponse = Invoke-McpServer -ServerPath $server -Messages $runMessages -TimeoutSec ($TimeoutSec + 90)
$run = $runResponse[-1].result.structuredContent

$julesStatus = "not_checked"
if ($env:JULES_API_KEY) {
  $healthMessages = @(
    $init,
    @{ jsonrpc = "2.0"; id = 2; method = "tools/call"; params = @{ name = "mcp_health_check"; arguments = @{ includeJules = $true } } }
  )
  $healthResponse = Invoke-McpServer -ServerPath $server -Messages $healthMessages
  $julesStatus = if ($healthResponse[-1].result.structuredContent.jules.apiKeyPresent) { "api_key_present" } else { "missing_api_key" }
} else {
  $julesStatus = "skipped_no_JULES_API_KEY_env"
}

$report = [ordered]@{
  generatedAt = (Get-Date).ToUniversalTime().ToString("o")
  status = $run.status
  toolRoot = $ToolRoot
  stateRoot = $StateRoot
  demoProject = $DemoRoot
  julesRoute = $julesStatus
  handoffId = $handoff.id
  resultPath = $run.resultPath
  resultReady = $run.result.ready
  agyExitCode = $run.exitCode
}

$reportPath = Join-Path $ReportDir "user-flow-demo-result.json"
$report | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $reportPath -Encoding UTF8

[pscustomobject]@{
  status = $run.status
  report = $reportPath
  demoProject = $DemoRoot
  handoffId = $handoff.id
  resultPath = $run.resultPath
  julesRoute = $julesStatus
} | ConvertTo-Json -Depth 8
